### ISSUE TITLE
Channel Currency, Giveaway Tool, Viewer Hours Watched, Chat Games and import from scorpbot

### ISSUE THREAD

**Issue by OutlawDade** [Firebottle/Firebot#536] opened 2018-02-18 18:32 UTC
Need that Loyalty Point system and a giveaway tool chat games like heist, roulette etc and track hours watched by viewers and a way to import that stuff from scorpbot and then i can solely use firebot.

**Comment by Firebottle** [comment] 2018-02-19 14:33
Yep, all of this is already on the list. It'll be a slow rollout and won't happen all at once.

**Comment by Firebottle** [comment] 2018-02-22 15:22
duplicate of #520 closing

**Closed** 2018-02-22 15:22 UTC
Labels: Feature Request, duplicate/invalid
