### ISSUE TITLE
Trouble seeing graphic on OBS

### ISSUE THREAD

**Issue by beambrit** [Firebottle/Firebot#82] opened 2017-03-01 01:34 UTC
Hi guys,

I am trying to upload a graphic to be triggered when a certain button is pressed and for some reason it is not showing up in OBS. I am using OBS 17.0.2 ftl 30 (64bit) My firewall is open. I uploaded my board, added graphic and sound, set duration for graphic, uploaded overlay in browser source in OBS, clicked button and I heard audio but there is no graphic. I tried using celebration on a different button and I was able to hear audio and see the fireworks. Not too sure if I am missing a step or if it is something else. 

![firebot help](https://cloud.githubusercontent.com/assets/26101485/23442183/ded808d8-fddb-11e6-817e-acbc025d5b0f.png)

**Comment by beambrit** [comment] 2017-03-01 01:36
![image](https://cloud.githubusercontent.com/assets/26101485/23442274/5f29a172-fddc-11e6-81c0-80886749c876.png)

**Comment by Firebottle** [comment] 2017-03-01 05:00
Hello! This sounds like the same problem we're working on in #78 . Which version of Firebot are you using? The newest beta version is supposed to address this issue.

**Comment by Firebottle** [comment] 2017-03-01 19:57
@beambrit I'm going to go ahead and close this issue as a duplicate of #78 . Make sure to comment on that threat if the newest release does not fix the issue you're having!

**Closed by Firebottle** 2017-03-01 19:57 UTC
Labels: question
