### ISSUE TITLE
Request: Custom Web API calls

### ISSUE THREAD

**Issue by murf-guy** [Firebottle/Firebot#136] opened 2017-06-02 14:26 UTC
I use a custom built web overlay that allows me to control on-screen events via API calls in ScorpBot by way of a PHP servlet. Part of my overlay/board includes buttons that are meant to be essentially spammed (they are emoticon reactions that appear on screen sort of like how Facebook's live videos show reactions). I have currently enabled this via the 'chat' style of button to trigger my API calls. However, either Mixer or ScorpBot doesn't process this spam in real time, and it's possible for someone to spam the reactions and tie up the bot for long enough that they can cause significant delays in other on-screen events (such as Follow alerts/other custom interactive overlay events) as these are run in order as ScorpBot receives them.

One potential way around this would be to have FireBot send the API calls to my servlet directly rather than chat commands. I do see that you currently have options for other API calls, and so was wondering if would be possible to include a bit of similar functionality that allows for a custom URL to be sent out when a button is clicked.

Thank you for your time and consideration of this request.

**Comment by Firebottle** [comment] 2017-06-03 04:23
Sure, it's something I've been wanting to add for awhile. Marking it as a feature request. Just to be transparent, since it is a pretty advanced thing it'll probably come after all of the basics are stable and working fine.

**Comment by ebiggz** [comment] 2017-06-06 06:29
This looks like a duplicate of issue #52. I am currently working on this feature and should have it done soon. 👍

**Comment by ThePerry-2015** [comment] 2017-06-06 12:01
Closing this as it's related to the issue ebiggz linked, #52 . No point in having duplicate issues open. Ideas and thoughts on this feature should be brought up in the other thread to keep the board clean and organized. :)

**Closed by ThePerry-2015** 2017-06-06 12:01 UTC
Labels: Difficulty: Hard, Feature Request

**Comment by Firebottle** [comment] 2017-06-07 20:25
@murf-guy as of v3.3.0 custom scripts are now in place.
