### ISSUE TITLE
Volume control for Video files

### ISSUE THREAD

**Issue by skillzNthrillz** [Firebottle/Firebot#262] opened 2017-07-05 03:12 UTC
#### Describe your issue or feature request:
It would be nice to lower the volume for my video files that are considerably louder than others. Would be much easier than having to edit them all in audacity or something like that.

-----------------------------------------------------------------------
#### If you're reporting an issue please fill out the steps below:

- What version of Firebot are you running?

- Have you tried the troubleshooting steps located on the wiki?

- Are you able to reproduce the issue? If so, what steps did you follow?

-----------------------------------------------------------------------
#### If you are having problems related to your interactive board, there are two ways that you can help us help you
**1)** Please navigate to **/firebot/user-settings/controls** and attach the .json file of the board you are having issues with.

**2)** Go to Mixer's Interactive Studio, click "Edit" on the board you are having issues with, click on the share icon beside the board name up top in the right corner of the page, choose "Only allow specific", and then add in our names (Firebottle, ebiggz, kateract, and ThePerry). This allows us to more easily test your board. Thanks!

**Comment by Firebottle** [comment] 2017-07-05 03:36
This is planned for V4.1.0

**Comment by Firebottle** [comment] 2017-07-05 13:08
Going to go ahead and close this one since it is a duplicate of #256 

After 4.0 is stable this will be one of the next things we add to videos. Youtube will also get a few new things such as a start and end time on the video.

Thanks for helping out @skillzNthrillz !

**Closed by Firebottle** 2017-07-05 13:08 UTC
