### ISSUE TITLE
Auto-reconnect option

### ISSUE THREAD

**Issue by Uriei** [Firebottle/Firebot#410] opened 2017-10-18 11:59 UTC
Just that, an option on the app to be able to auto-reconnect both Interactive and Chat if they disconnect for any reason.

**Comment by Uriei** [comment] 2017-10-18 21:41
Also, another thing I noticed and it's a bit annoying too, is that you can't turn on both connections at the same time, not even one after another in quick succession, you have to wait for one to finish the connection process to do the other one, so it would be nice to remove that "cooldown" or make a "Connect all" button, also the hotkey tooltip for the Chat one is wrong, it says F12 when it's F11.

**Comment by Firebottle** [comment] 2017-10-25 13:32
Yes, you need to wait between connections. This is because each time you connect it gets a new oauth refresh token. If you connect both at the same time it throws that token out of sync and you would need to completely re-log into the app.

**Comment by Firebottle** [comment] 2017-10-25 13:40
closing as duplicate of #343

**Closed by Firebottle** 2017-10-25 13:40 UTC
Labels: Feature Request
