### ISSUE TITLE
Using a board with more than 2 scenes causes bot to not connect.

### ISSUE THREAD

**Issue by DakotaBlake** [Firebottle/Firebot#135] opened 2017-06-02 05:24 UTC
As the title says, I have a board with 3 scenes. Using 2 scenes with the original 2 boards, everything works fine. Adding a third causes Mixer to display "Waiting for game" and the app's connect button stays red.

**Comment by Iampanzer** [comment] 2017-06-02 07:28
I had 4 boards i deleted 2 to see if that worked for me, nope. I cant get them to work either

**Comment by Firebottle** [comment] 2017-06-02 15:03
Just tested three scenes and I was able to connect fine. What are the names of your scenes?

![capture](https://cloud.githubusercontent.com/assets/17416635/26731767/b37bcab0-477a-11e7-8519-1fe593621ad9.JPG)

**Comment by Firebottle** [comment] 2017-06-02 15:07
Also, try going through every scene and button you have and hitting save. No need to edit settings, just hit the save button.

**Comment by DakotaBlake** [comment] 2017-06-02 20:16
The scene I added only had a button to return to previous scene. Just a single normal button.

**Comment by Firebottle** [comment] 2017-06-02 23:54
Okay, I am unable to reproduce on my side. Can you follow the troubleshooting steps and if you still have issues follow the instructions in the bottom part. I need you to share your board with me and attach the controls json file.

https://github.com/Firebottle/Firebot/wiki/Troubleshooting

**Comment by ThePerry-2015** [comment] 2017-06-06 11:54
Any updates on this issue? If not it should be closed. I've just tested this with Firebot 3.2.0 with 5 scenes and Firebot still connects without issues as well as triggers scene shifts both via buttons and group assignment.

**Comment by Firebottle** [comment] 2017-06-06 13:12
Closed as it's been 4 days and a few updates since any response.

**Closed** 2017-06-06 13:12 UTC
Labels: Support
