### ISSUE TITLE
v3.2.0 Cooldown other buttons leaving out certain buttons for no reason

### ISSUE THREAD

**Issue by Kylix-Tyfurious** [Firebottle/Firebot#162] opened 2017-06-06 12:47 UTC
I've attached reference images, but when I press 'wriggity wrekt' it is suppose to cool down all other buttons for 10s, but it's not cooling down 'wow!' and vice versa, when I press 'wow!' it's not cooling down 'wriggity wrekt' even though they are on each other's list. Not sure what's causing that, but I can't find a work around for it.

![buttons issue](https://cloud.githubusercontent.com/assets/29049332/26829769/b9d90bc6-4a94-11e7-8484-1b55d283e4d0.PNG)

![cooldown issue](https://cloud.githubusercontent.com/assets/29049332/26829770/bc2f6e2e-4a94-11e7-93bf-cd5d5d09e766.PNG)

**Comment by Firebottle** [comment] 2017-06-06 13:06
duplicate of #159

**Comment by ThePerry-2015** [comment] 2017-06-06 15:29
Are you sure this is a duplicate @Firebottle ? I have this issue right now with the 2.3.1 update.

Repro: Add a cooldown group assign a couple of buttons, then go to one of the buttons that are included in the cooldown group and add a cooldown effect to a couple of other buttons. Then save and click one of the buttons included in the cooldown group. Then it will show you all the other buttons in the group on cooldown except the one that has it's own cooldown effect added to it. The same if you press this button, the other buttons in the group will be on cooldown as well as the buttons added to the cooldown effect but not itself.

**Comment by Firebottle** [comment] 2017-06-06 16:01
I'll reopen and test this out. Thanks!

**Comment by Firebottle** [comment] 2017-06-06 16:33
Found the issue. This wasn't a duplicate, but it was caused by the exact same bug that was fixed for cooldown groups in 3.2.1. 

Basically when an individual control was saved it was removing the setting for the scene that button was attached to. So when it tried to reach out to mixer to get the control to cool down it was sending over "undefined" for the scene name.

Will be rolling out a patch for this shortly.

**Comment by Firebottle** [comment] 2017-06-06 16:56
https://github.com/Firebottle/Firebot/releases/tag/3.2.2

Please let me know if this fixes the issue.

**Comment by ThePerry-2015** [comment] 2017-06-06 17:05
That seems to fix the issue, at least on my end.

**Comment by Kylix-Tyfurious** [comment] 2017-06-06 17:31
Hmm, @Firebottle 3.2.2 is giving me an issue now where the buttons don't do anything at all and the board turns off even though it's still connected. Here's a short video so you can see what's happening.

https://streamable.com/f4ki0

**Comment by Firebottle** [comment] 2017-06-06 17:51
Yes sorry... that was my fault. Give 3.2.2 another download. @Kylix-Tyfurious 

Removed clientid to merge dev into master, and forgot to re-add it when running the build.

**Comment by Kylix-Tyfurious** [comment] 2017-06-06 18:19
@Firebottle Redownloaded and tried again. Buttons on Mixer still aren't responding.

I just now downloaded 3.2.2 again from the link you gave earlier https://github.com/Firebottle/Firebot/releases/tag/3.2.2

Then I dragged the folder over and replaced all the existing stuff, but it didn't seem to have any effect on the issue. Did I do something wrong?

**Comment by Firebottle** [comment] 2017-06-06 18:26
Does the moderation tab show anything when hitting those buttons?

**Comment by Kylix-Tyfurious** [comment] 2017-06-06 18:32
Only when I press the buttons manually from the program, nothing when I press it from the site.

**Comment by Firebottle** [comment] 2017-06-06 18:34
Okay try just going into each button and cool down group and hitting save.

**Comment by Kylix-Tyfurious** [comment] 2017-06-06 18:57
Resaved all buttons, but it's still not working from the site after connecting. Nothing in moderation tab, but the buttons still trigger manually from the program. I'll try to redownload again and restart PC too for good measure.

**Comment by Firebottle** [comment] 2017-06-06 18:59
If that doesn't work then I'll need you to share your controls file and board with me. The controls file can be found in /firebot/user-settings/controls/game-name.json. To share your board go to your board in the mixer studio and his the share icon in the top right, then put in my username.

**Comment by Kylix-Tyfurious** [comment] 2017-06-06 19:08
Alright, here's the .json 
https://drive.google.com/open?id=0B8Yo0Os_yTMsSVppX21kM3VpVWs

And I added 'Firebottle' to the board. There were a few different ones, so hopefully the was the correct one.

**Comment by Firebottle** [comment] 2017-06-06 19:25
Can you try this for me real quick and give me some feedback? @Kylix-Tyfurious 

https://github.com/Firebottle/Firebot/releases/tag/v3.2.3

**Comment by Kylix-Tyfurious** [comment] 2017-06-06 19:53
After trying 3.2.3, everything seems to be fixed for both issues #161 and #162! That's amazing!

But there is a common occurrence now where the tab becomes completely unresponsive in Chrome after pressing a few buttons. The spinning cooldown wheels stop moving and the page can't be scrolled up or down. Refresh won't fix the page either. Only closing the entire tab and opening the page in a new one fixes it. (If you wait too long for the page to refresh, the error message from Chrome says "Chrome ran out of memory trying to display this webpage" if that helps at all.)

Once I get the new tab up,, the board no longer reflects the fact that anything is on cooldown. All buttons are available to press again immediately.

Is that a Firebot issue or something on Mixer's end? I'm not sure because I've never gotten this far with Interactive 2.0 haha.

Also, thank you so much for putting so much work into helping everyone @Firebottle!

p.s.
I did find an additional issue with cooldowns overwriting something already on cooldown. If I need to open a new thread I can. When a button is on cooldown for 3min and I press another button that would normally only make it cooldown for 10s, the 10s cooldown overwrites the already active 3min cooldown so the button can be pressed in 10s now instead of 3min. Hopefully I explained that correctly. I can provide a video if that would make it easier to understand.

Seems like it just needs some kind of 'if button is already on cooldown, don't place the new cooldown over it' line or something. (I know nothing about programming, lol.)

**Comment by Firebottle** [comment] 2017-06-06 19:55
Unfortunately the memory issue and the cooldowns not showing after refresh are both Mixer issues. I've reported both of those and they're working on fixes.

For that last bit, I understand what you're saying. I'll open up a new feature request with the info you posted.

**Closed** 2017-06-06 19:56 UTC
Labels: bug
