### ISSUE TITLE
3.4.1 - "Error Pressing Button" msg / Board disconnected repeatedly

### ISSUE THREAD

**Issue by Kylix-Tyfurious** [Firebottle/Firebot#284] opened 2017-07-19 15:14 UTC
#### Describe your issue or feature request:

Update 2: I am now using the 4.0 beta 5 and I'm still getting these same problems. It was a different button this time, but it said "Error Pressing Button" even when I tried to manually activate it from the software. It's nothing crazy; a simple [Ctrl]+[F1] press. Works for a while, then seems to break. 

Update 1: I tried the board again today after removing the button I thought was causing the issue, but other buttons started to say Error Pressing Button as well. So I'm not sure what's causing this issue, but I can't use interactive at all until I figure out how to fix it.

The board was working perfectly for about 5/6 hours, then suddenly, one button on my board (I think it was the only offender, but not sure) would cause the software to display an "Error Pressing Button" message and the board would disconnect. I restarted the board and then it would keep happening. 

The viewers were getting charged sparks, but the board would error out and the interaction would not trigger.

Any reason why this might have happened after working perfectly for so long? It seemed to happen after a spike in viewers, but even restarting Firebot didn't seem to help.

I checked the button settings and everything looked normal. It was strange because the button that was causing the issue had been pressed many times during the stream and seemed to work just fine until that issue happened.

It wouldn't be so bad if it didn't keep charging viewers 500+ sparks each time, but I couldn't figure out what was causing it, so hopefully you guys can help! 

As always, thank you!

-----------------------------------------------------------------------
#### If you're reporting an issue please fill out the steps below:

- What version of Firebot are you running?
3.4.1

- Have you tried the troubleshooting steps located on the wiki?
Yes.

- Are you able to reproduce the issue? If so, what steps did you follow?
Sort of, but it costs viewers sparks to reproduce. They were pressing my "2 spooky" button and then the board would charge them sparks and disconnect without triggering the interaction.
-----------------------------------------------------------------------
#### If you are having problems related to your interactive board, there are two ways that you can help us help you
**1)** Please navigate to **/firebot/user-settings/controls** and attach the .json file of the board you are having issues with.

https://drive.google.com/open?id=0B8Yo0Os_yTMsZ0JIM2tCbnZrUWM

**2)** Go to Mixer's Interactive Studio, click "Edit" on the board you are having issues with, click on the share icon beside the board name up top in the right corner of the page, choose "Only allow specific", and then add in our names (Firebottle, ebiggz, kateract, and ThePerry). This allows us to more easily test your board. Thanks!

Done!

**Comment by Firebottle** [comment] 2017-07-27 21:16
I don't see anything right off the bat in the controls file that might cause it. Have you tried creating the same control on a blank board and trying again to see if it has the same issue?

**Comment by Kylix-Tyfurious** [comment] 2017-07-27 22:14
I haven't tried that yet. Trying to work out some cool down issues with 4.0 b5 at the moment. Once I get that sorted out, I'll revisit this error pressing button issue. Do you mean I need to rebuild my entire board again? It's weird that this issue only seems to occur after the board has been working flawlessly for a while, but once it starts, even restarting the board doesn't seem to fix the issue. Would be hard to duplicate I think.

**Comment by Firebottle** [comment] 2017-07-30 01:41
This is going to be EXTREMELY hard to reproduce I think. Can you update to 4.0.0 that we just released and try that? It has log files that might help us hunt down the issue.

**Comment by Firebottle** [comment] 2017-07-31 13:15
Going to go ahead and close this one since it's aimed at an older version. If you happen to run into this issue again with 4.0 please go ahead and let us know.

**Closed by Firebottle** 2017-07-31 13:15 UTC
Labels: Support
