### ISSUE TITLE
All images only show the "broken image" block.

### ISSUE THREAD

**Issue by Dernial** [Firebottle/Firebot#78] opened 2017-02-23 03:33 UTC
So, I'm sure it's just me. But I can't get media working at all.

When I load the overlay page in the browser, it works.
When I created an HTML page, loaded it up as an overlay in OBS, it worked.

I've tried static images, and animated gifs.

The event is running because I have an audio associated as well, and the audio plays.

Using version 2.2.2
OBS 17.0.2

Beam JSON:
`{
  "reportInterval": 50,
  "tactiles": [
    {
      "id": 0,
      "type": "tactiles",
      "blueprint": [
        {
          "width": 2,
          "height": 1,
          "grid": "large",
          "state": "default",
          "x": 0,
          "y": 0
        }
      ],
      "analysis": {
        "holding": false,
        "frequency": true
      },
      "text": "Cheer?",
      "cost": {
        "press": {
          "cost": 0
        }
      },
      "cooldown": {
        "press": 0
      }
    }
  ],
  "joysticks": [],
  "screens": []
}`

**Comment by Firebottle** [comment] 2017-02-23 04:44
What steps are you taking to load the html overlay file into obs?

**Comment by Dernial** [comment] 2017-02-23 04:55
New Source -> Browser Source -> Create new
Check Local file.
Click browse.
Select Firebot-win32-x64/overlay/firebot.html
Change width/height to full screen size.
Clear CSS box.
Check Shutdown source when not visible.
Check Refresh browser when scene becomes active.

I upgraded. I want to say it wasn't working on 2.2.0, but I can't remember.

I just went fresh, same thing.

**Comment by ThePerry-2015** [comment] 2017-02-23 08:53
@Dernial When you open the firebot overlay in a browser, can you inspect or view the source and find the URL for the image that is popping up and see how it's formated? You have to trigger the button so you see the code change in the overlay to see the URL it uses.
This is how it looks on my end:
```
<div class="1487839759793-image middle">
    <img src="file://F:\Downloads\old\Happy-new-year-from-Norway.gif?time=1487839759793">
</div>
```

Note: I just tested this with a brand new download of 2.2.2 and placed it in a new folder to start fresh and my animated gif plus sound file works just fine. I also tried to remove user-settings and copy in an old user-settings folder from a previous version and added the image plus sound at that worked just fine as well. 

Using OBS 17.0.2.ftl-32 (64 bit Windows) and Firebot 2.2.2 from the release page.

**Comment by Dernial** [comment] 2017-02-23 14:40
This is what I got when loaded up in firefox.
```
<div class="1487854829395-image middle" style="">
  <img src="file://G:\Streaming\Justice\Untitled=1.gif?time=1487854829395">
</div>
```
I just wiped out OBS and settings. Downloaded OBS-Studio 17.0.2 with FTL.32. Fresh install, added overlay and tested. The sound played, but I didn't get the image or the broken image icon.

Reinstalled OBS without FLT, broken image icon.

**Comment by Firebottle** [comment] 2017-02-23 16:30
Can you download the attached main.txt and change the filename to main.js, then overwrite firebot/overlay/js/main.js? After that try restarting OBS and see if it makes any difference for you.

Download:
[main.txt](https://github.com/Firebottle/Firebot/files/797062/main.txt)

**Comment by Dernial** [comment] 2017-02-23 22:11
Just tried... No luck.

From playing with it, I can link the image in the overlay just fine, but I had to put the <img /> tag in the wrapper div. I added a bit to the main.js to move the added div in there, but still doesn't work. I even took it out of the div to reference it to delete it after.

I started digging for log files, I can't seem to find any logs for the browser source. I did find the following in my OBS logs though.

```
16:04:43.918: Required module function 'obs_module_load' in module '../../obs-plugins/64bit/chrome_elf.dll' not found, loading of module failed
16:04:43.922: [CoreAudio encoder]: Adding CoreAudio AAC encoder
16:04:43.923: [AMF Encoder] Unable to load 'amfrt64.dll', error code 126.
16:04:43.929: Required module function 'obs_module_load' in module '../../obs-plugins/64bit/libcef.dll' not found, loading of module failed
16:04:43.930: Required module function 'obs_module_load' in module '../../obs-plugins/64bit/libEGL.dll' not found, loading of module failed
16:04:43.930: Required module function 'obs_module_load' in module '../../obs-plugins/64bit/libGLESv2.dll' not found, loading of module failed
16:04:43.930: Failed to load 'en-US' text for module: 'obs-browser.dll'
```

Googled a whole bunch on the errors, found a reference to it may be the AV. Disabled that, reinstalled... even removed AV completely and reinstalled.

I'm pretty much running out of ideas.

**Comment by Firebottle** [comment] 2017-02-23 22:34
Have you tried deleting the OBS Browser cache yet? I think there is a button for it in the settings for the source, but you could also try going to the folder and manually deleting it.

%appdata%\obs-studio\plugin_config\obs-browser

It sounds like you know a little bit of coding. You could try just throwing the image tag itself into the HTML file to see if that shows up at all and just ignore all of the javascript. If it still doesn't show at that point I'll be really confused.

**Comment by Dernial** [comment] 2017-02-23 22:51
Ok. I finally got it to work. I deleted the cache. Removed the file:// from the JS. Placed the image I wanted in the overlay directory and used just the filename in the button's media input box.

Now the question is... why?

**Comment by Firebottle** [comment] 2017-02-23 22:53
So, my guess is that it was the caching issue. OBS is notoriously bad at caching browser assets. I'm assuming that it cached the first version you loaded into OBS and then ignored the updated js when you went to version 2.2.2.

**Comment by Dernial** [comment] 2017-02-23 22:54
I don't think it was the cache. I did try deleting that, and leaving stock files, and it didn't work.. I basically had to make it use a local file to get it to work.

**Comment by Firebottle** [comment] 2017-02-23 22:55
OH ... do you by chance have firebot in a program files directory?

**Comment by Dernial** [comment] 2017-02-23 22:56
Nope. G:/Streaming/Firebot-win32-x64/

**Comment by Firebottle** [comment] 2017-02-23 22:58
Try running firebot as an administrator and throwing the image in the regular way.

**Comment by Dernial** [comment] 2017-02-23 22:59
Nope. Broken image icon.

**Comment by Firebottle** [comment] 2017-02-23 23:06
I'm out of ideas right now. Could you go into your user-settings/controls folder and throw the JSON for the board your using into a txt file and attach it? I'll see if I can make the problem happen on my side.

**Comment by Dernial** [comment] 2017-02-23 23:09
[Overwatch.txt](https://github.com/Firebottle/Firebot/files/797949/Overwatch.txt)

**Comment by JimmyMac3** [comment] 2017-02-25 21:27
I can confirm same thing happening to me - OBS-Studio Browser Source shows nothing - Chrome shows the image just fine. 

Removing the File:// from the image processor section of main.js fixes the problem. I put all my images in the same folder as Firebot.html and remove the path leaving filename only and everything works because removing file:// changes the link from an absolute to a relative link.

There is some discussion on Absolute links not working in the OBS-Studio Browser Source Plugin - There is a mention of using http://absolute/FULL-PATH/FILENAME so I attempted to change the File:// to http://absolute/ but no difference still won't display the image in OBS - The relative link workaround works for me so I'm good for now.

**Comment by Firebottle** [comment] 2017-02-26 06:12
@ThePerry-2015 was talking about maybe having the app make a copy of the image you choose and put it into the firebot folder before using. That could happen, but as a user I think it would be annoying to have your files duplicated.

Still looking into it.

**Comment by Firebottle** [comment] 2017-02-27 00:26
According to the browser source creator OBS uses http://absolute instead of file://. So, I'll need to put a new setting in the app for OBS compatibility mode that will send that path instead of file://. 

Source:
https://obsproject.com/forum/threads/browser-source-classic-vs-studio.43867/#post-197540

**Comment by Firebottle** [comment] 2017-02-27 02:14
Released update 2.2.3 Beta 1. This adds an OBS compatibility option in the settings area that changes the file path sent to the overlay to this weird http://absolute workaround the browser source creator put together.

If you're having issues download it and give me some feedback!

Download:
https://github.com/Firebottle/Firebot/releases/tag/v2.2.3-beta.1

**Comment by Dernial** [comment] 2017-02-28 04:13
Seems to have fixed it for me. I would rename the option though, maybe just make it a check box. The naming of the option seems... odd.

**Comment by Firebottle** [comment] 2017-02-28 04:37
Well, it is compatibility mode haha. http://absolute is 100% a workaround that the browser source creator put in place. It won't work in anything else. XSplit and any other client I know of would be using file:///

**Comment by Dernial** [comment] 2017-02-28 04:39
Change it to "Fix derpy OBS plugin that doesn't follow standard HTML notation." ?

**Comment by Firebottle** [comment] 2017-02-28 04:39
hahah

**Comment by Dernial** [comment] 2017-02-28 04:40
It's more descriptive that way.

**Comment by Firebottle** [comment] 2017-02-28 04:41
I'll see if I can put some text in a tooltip somewhere to explain and update the FAQ in the wiki. Might also just change it to "OBS" in the dropdown.

Anyway, I'll leave this open for a few days. If anyone else has a chance to test please let me know.

**Comment by SpontaneousJ** [comment] 2017-03-01 19:01
I can say I have tested this 2.2.3-beat.1 and I am no longer getting the broken image but I am not getting any image.  I have cleared browser cache as suggested.

**Comment by Firebottle** [comment] 2017-03-01 19:53
@SpontaneousJ and you've set the media option in the settings area to OBS compatibility?

**Comment by SpontaneousJ** [comment] 2017-03-01 20:06
OBS compatibility was not selected.... I had failed, but you have saved me!  It is working.

**Comment by Firebottle** [comment] 2017-03-01 20:22
Huzzah! (I should probably make it more obvious that option is there though!)

I went ahead and released the version you guys tested as a full release since it seems to be working. Thank you guys so much for the help and please let me know if you ever run into problems. 

Going to go ahead and close this issue for now. Please open a new issue if you run into the problem again.

**Closed by Firebottle** 2017-03-01 20:22 UTC
Labels: bug, Needs Testing, Priority
