### ISSUE TITLE
4.0 full release - After some time, program only shows a white box and needs to be restarted

### ISSUE THREAD

**Issue by Kylix-Tyfurious** [Firebottle/Firebot#299] opened 2017-07-31 14:53 UTC
#### Describe your issue or feature request:

This only happened 2 times to me during an 8 hour stream, but at some point, viewers pointed out to me that the board was rip. When I looked at the Firebot software, the entire window was white. I had to close out of it and reopen it. It seemed to fix the issue, but it happened later in the stream. 

Not sure what caused it, but I wanted to drop the feedback in here in case it was an unknown issue. 

Loving the new version by the way. It's been working great so far! Thank you guys, sincerely.

-----------------------------------------------------------------------
#### If you're reporting an issue please fill out the steps below:

- What version of Firebot are you running? Might be an idea to update to the latest version to see if the issues has been resolved there before posting an issue if you are on an old version(4.0.0 is the latest).

4.0 full release

- Have you tried the troubleshooting steps located on the wiki?

n/a

- Are you able to reproduce the issue? If so, what steps did you follow?

Cannot seem to pinpoint how it happens, but it did occur twice during an 8 hour stream with 90+ viewers.

-----------------------------------------------------------------------
#### If you are having problems related to your interactive board, there are two ways that you can help us help you, please do BOTH of these steps as it makes it a LOT easier to help you to investigate the issue.
**1)** Please navigate to **Settings -> Open Root Folder** Then open user-settings -> controls and attach the .json file of the board you are having issues with, as well as the **latest log file in the user-settings -> logs folder** put these files in a ZIP-file before attaching them.

**2)** Go to Mixer's Interactive Studio, click "Edit" on the board you are having issues with, click on the share icon beside the board name up top in the right corner of the page, choose "Only allow specific", and then add in our names (Firebottle, ebiggz, kateract, and ThePerry).
This allows us to easily test your board. Thanks!

**Comment by Firebottle** [comment] 2017-07-31 15:20
Thanks for the report! Could you check to see if a log file was generated? This should be in your user-settings/logs folder.

**Comment by ebiggz** [comment] 2017-08-01 20:46
Open Firebot, go to Settings, and in the General tab, click "Open Root Folder"

**Comment by Kylix-Tyfurious** [comment] 2017-08-01 23:08
I went to the user-settings folder via the "open root folder" option, but I don't see any logs folder or file. 

I only see auth, groups and settings .json and controls, overlay-settings and scripts folders.

I guess this issue didn't generate any log files?

**Comment by Firebottle** [comment] 2017-08-01 23:27
Could be! I have another person who had the same issue and gave a few steps to reproduce. So we'll look into that and hopefully get it fixed up with those steps.

**Comment by Firebottle** [comment] 2017-08-02 14:07
After some research, the white screen problem is definitely related to winston. Working on a fix for it now.

**Comment by Firebottle** [comment] 2017-08-02 14:26
Okay, this is fixed and should be released in the next version. Issue was due to winston not being able to find the error log folder after we changed the user settings path. We also weren't creating the error log folder on application startup.

**Comment by Firebottle** [comment] 2017-08-03 00:32
release 4.0.1

**Closed by Firebottle** 2017-08-03 00:32 UTC
Labels: bug, Dev Complete
