### ISSUE TITLE
Gifs not displaying in OBS at all

### ISSUE THREAD

**Issue by TyleriumGaming** [Firebottle/Firebot#261] opened 2017-07-05 02:37 UTC
#### Describe your issue or feature request:

Nothing as far as gifs or images display in obs whatsoever. Using OBS 18.0.1-ftl.0.9.4 and using Firebot release 3.4.1. Images are not working!!!

-----------------------------------------------------------------------
#### If you're reporting an issue please fill out the steps below:

- What version of Firebot are you running?

- Have you tried the troubleshooting steps located on the wiki?

- Are you able to reproduce the issue? If so, what steps did you follow?

-----------------------------------------------------------------------
#### If you are having problems related to your interactive board, there are two ways that you can help us help you
**1)** Please navigate to **/firebot/user-settings/controls** and attach the .json file of the board you are having issues with.

**2)** Go to Mixer's Interactive Studio, click "Edit" on the board you are having issues with, click on the share icon beside the board name up top in the right corner of the page, choose "Only allow specific", and then add in our names (Firebottle, ebiggz, kateract, and ThePerry). This allows us to more easily test your board. Thanks!

**Comment by JimmyMac3** [comment] 2017-07-05 02:51
Same problem here and I updated to 4.0.0 Beta 4 and it i doesn't help - The issue actually is the overlay doesn't work at all in OBS BrowserSource - Show Image, Show Video, Fireworks all do nothing now in OBS - Loaded up /firebot/overlay/firebot.html in Chrome and it works just fine when buttons pressed - Fireworks even display fine in chrome.

**Comment by ThePerry-2015** [comment] 2017-07-05 07:59
Just a couple quick question from me, what settings do you guys use for the overlay in Firebot?
Version 4.0.x: Settings -> Overlay -> Overlay Compatibility.
Version 3.x: Settings -> Overlay Compatibility.

And how are you loading the overlay into the OBS browser source?
If Firebot settings is set to OBS it has to be loaded as C:/this/is/my/path/to/Firebot v3.4.0/overlay/firebot.html with a check mark on Local File.
If Firebot settings is set to Other it has to be loaded as file:///c/this/is/my/path/to/firebot/overlay/firebot.html without a check mark on Local File

If you are using the OBS overlay setting this will show broken images in the overlay when testing in Chrome since Chrome doesn't understand the paths given in the overlay from Firebot for OBS Compatibility since OBS requires some weird URLS to be able to use "local files".
Videos should be fine, same with fireworks and HTML button effects.

**Comment by JimmyMac3** [comment] 2017-07-05 16:45
Version 4.0.x: Settings -> Overlay -> Overlay Compatibility - Set to OBS
OBS BrowserSource - Local File CHECKED & path=E:/Documents/Firebot-win32-x64/overlay/firebot.html

With those settings the overlay never shows any images / fireworks

Because of what you asked I just changed my settings in OBS to
OBS BrowserSource - Local File UNCHECKED & URL=file:///E:/Documents/Firebot-win32-x64/overlay/firebot.html

Now images and fireworks are showing up no matter if Overlay Compatibility is set to OBS or OTHER

**Comment by ThePerry-2015** [comment] 2017-07-05 17:34
Yeah, when not using Local File in OBS it seems to work regardless of setting in Firebot, but if you have Local File set in OBS it breaks if Firebot is set to Other.
I have no issues what so ever using Local File and setting Firebot to OBS so I'm not sure why it doesn't work on your end.

TyleriumGamings issue is apparently port related according to his and Firebottles chat on Discord earlier today/late night yesterday depending on your timezone.. xD

Hopefully we will manage to solve both issues. :)

**Comment by ThePerry-2015** [comment] 2017-07-05 19:00
Just created a Wiki page about troubleshooting Overlays problems in OBS Studio: https://github.com/Firebottle/Firebot/wiki/Troubleshooting-Firebot-Overlay-issues-in-OBS-Studio
Just adding a pointer to it here as well for "safe keeping" and reference. :) This one might help you in figuring out why it's not working when you use Local File @JimmyMac3

**Comment by TyleriumGaming** [comment] 2017-07-05 19:48
I am using Browsersource when loading in the overlay and 'Local file' is
checked. I re-installed the old version and left the beta version and now
gifs and images are working again. I hope whatever is wrong can get
resolved between the new version and OBS.

**Comment by Firebottle** [comment] 2017-07-05 20:16
@TyleriumGaming Did you switch back to 3.4.1? If so, what are your settings set to in that version?

**Comment by Firebottle** [comment] 2017-07-06 04:20
Uploaded beta 5 which might help with this one. Beta 4 was not creating the appropriate folders for new users on startup. 

If you'd like to give beta 5 a chance it's not available. Otherwise, we can go ahead and close this thread.

**Comment by Firebottle** [comment] 2017-07-09 21:48
Closing this as no response in 4 days. Beta 5 should have fixed the issue. It was likely caused by folders not being created for new users.

**Closed by Firebottle** 2017-07-09 21:48 UTC
Labels: Support
