### ISSUE TITLE
Key Modifiers Are Lost Randomly/After Key Use

### ISSUE THREAD

**Issue by Thompson-Kaa** [Firebottle/Firebot#206] opened 2017-06-23 03:25 UTC
#### Describe your issue or feature request:

Here is a link to my current backend: https://drive.google.com/file/d/0Bw1PyfFtlzXsZ0duY0l2cTJLNFE/view?usp=sharing

While using my current setup, key modifiers, specifically ctrl and alt, appear to get randomly removed from my controls. It seems to only happen to my special keys(ie. I AM READY, Shift Left/Right, Zero, etc.). This has happened during two streams so far, but I have not had time to debug it as I originally thought it was a configuration issue from porting from 3.4.0 to 3.4.1.

-----------------------------------------------------------------------
#### If you're reporting an issue please fill out the steps below:

- What version of Firebot are you running?
3.4.2

- Have you tried the troubleshooting steps located on the wiki?
No because I'm a terrible person.

- Are you able to reproduce the issue? If so, what steps did you follow?
It appears to happen randomly during use.

- Have you gone to /firebot/user-settings/controls and attached the problem controls file to this issue?
I don't know what that means.

- Go to Interactive Studio, edit the board in question, click on the share icon beside the board name up top in the right part of the view. Choose only allow specific .... then type in our names and click add and you should be ok. (Firebottle, ebiggz, kateract and ThePerry)

**Comment by ThePerry-2015** [comment] 2017-06-23 05:42
This is a duplicate of #172

**Closed by ThePerry-2015** 2017-06-23 05:42 UTC
Labels: duplicate/invalid

**Comment by ThePerry-2015** [comment] 2017-06-23 05:45
> Have you gone to /firebot/user-settings/controls and attached the problem controls file to this issue?
I don't know what that means.

This just asks you to share your controls file with us, like you did with the Google Drive link to your json file..
So you kind of understood it without knowing that you did.. ;)
