### ISSUE TITLE
Feature Request - 4.0.1 - Update Download Progress Bar

### ISSUE THREAD

**Issue by Kylix-Tyfurious** [Firebottle/Firebot#306] opened 2017-08-03 03:45 UTC
During the automatic update to 4.0.1, the software told me it was downloading the new version, but eventually stalled out. It sat there for a few minutes or more just spinning before the message popped up. This got me wondering, would there be any way to setup a % bar so users can see how much progress is being made during a download?

**Comment by ebiggz** [comment] 2017-08-03 04:11
We would love this too but frustratingly the framework we use to do the autodownload and install doesn't provide us with progress updates. We've explored alternatives that do provide progress updates, we may end up switching to one eventually

**Comment by Firebottle** [comment] 2017-10-03 15:33
I believe biggz already has this done as part of #375

**Comment by Firebottle** [comment] 2017-10-09 13:39
Ran into some issues incorporating the new updater. This will need to come in a later release.

**Comment by Firebottle** [comment] 2017-11-09 14:38
I'm going to go ahead and close this for now as it is a duplicate of #375.

**Closed by Firebottle** 2017-11-09 14:38 UTC
Labels: Difficulty: Hard, Feature Request
