### ISSUE TITLE
Scene Change

### ISSUE THREAD

**Issue by fyrebug72** [Firebottle/Firebot#312] opened 2017-08-03 14:01 UTC
#### Describe your issue or feature request (details are helpful!):
I have set a custom group for my Gamewisp subs. I have several scenes for my viewers. One of the scenes is for the Subs group. I have set up the Subs button to allow only subs to change to the Sub scene but it is not working. The mods are able to switch between their scene and the default scen with no problem.

-----------------------------------------------------------------------
#### If you're reporting an issue, *please* fill out & do the following:

- What version of Firebot are you running?
4.0.1

- What are the steps to reproduce the issue?
1)Having a sub user try the sub button
[Fyrebug Files.zip](https://github.com/Firebottle/Firebot/files/1197413/Fyrebug.Files.zip)

2)
3)

- (IMPORTANT) Go to Firebot's root folder (**Settings tab -> Open Root Folder**) then zip the following two files and attach that zip to this issue:

1) In **user-settings > controls**, find the .json file with the name of the board you are having issues with.
2) In **user-settings > logs**, find the latest log file.

```
NOTE: A lot of issues can be solved by,
- Updating to the latest version
- Trying the troubleshooting steps on the wiki
```

**Comment by Firebottle** [comment] 2017-08-03 14:31
Spoke with Fyre on discord to help address the problem. The issue is that the custom group was called "Subs" but "Subscribers" had been selected on all of the buttons. Since these are two different groups the buttons did not switch the people he was expecting.

Fix:
Go through your buttons and make sure you're selecting "Subs" everywhere instead of "Subscribers". If you have the "Subscribers" group on any button, make sure to remove it otherwise you could get errors.

**Comment by Firebottle** [comment] 2017-08-03 15:12
Going to go ahead and close this for now. If you're unable to get the fix to work just let us know.

**Closed by Firebottle** 2017-08-03 15:12 UTC
Labels: Support

**Comment by fyrebug72** [comment] 2017-08-03 17:06
kk ty
